### ISSUE TITLE
Initialize BeefyWorker validator set id for out-of-sync BEEFY gadget/client

### ISSUE THREAD

**Issue by adoerr** [paritytech/grandpa-bridge-gadget#112]
From #95 

> So this obviously works for now, but what if the client is not fully in sync with the network? I think we need a bit more sophisticated mechanism, where we actually update the validator set id when new blocks are imported / we get synced up.

Currently the `BeefyWorker` validator set id is always initialized by using `BeefyApi::validator_set()`. This assumes the client is synced with the network and that the `beefy_pallet` session handler has seen all relevant `on_new_sesseion()` calls.

As per the above comment, this approach is not sufficient for an out-of-sync client.

**Comment by tomusdrw** [comment]
Related #183
We need to be notified by the block import pipeline about already seen justifications and defer starting the gadget when major sync is on-going.

**Comment by seunlanlege** [comment]
can be closed now that  paritytech/substrate#10882 is merged

**Comment by acatangiu** [comment]
The issue description is a bit outdated so I will provide an update here.

With Lean BEEFY a node coming online at session N doesn't currently have a way to sync older mandatory BEEFY blocks to get the uninterrupted authority hand-offs chain. Instead, when mandatory block N is BEEFY-finalized, it assumes the finalizing super-majority of validators is honest. The node starts voting in session N+1 based on the finalized mandatory BEEFY block N authority set hand-off.

This issue tracks a way for the node to start voting - in lean beefy just wait for gossip of some mandatory block justification, then start voting on next session based on it - which is implemented.

Support for having the node able to vote as soon as sync is done is tracked in https://github.com/paritytech/grandpa-bridge-gadget/issues/183

So yes, we can mark this issue fixed by https://github.com/paritytech/substrate/pull/10882.
