### ISSUE TITLE
Reduce gossip on past rounds

### ISSUE THREAD

**Issue by tomusdrw** [paritytech/grandpa-bridge-gadget#182]
Let's try to optimize the gossip a bit by sending votes for **last round** to all peers that we know (like right now),
but let's limit the number of peers that we send votes from rounds `[last-5; last-1]` to `sqrt(peers)`.

This should reduce excessive gossip, but without being super complicated to implement.

**Comment by ordian** [comment]
@andresilva I'm not familiar with beefy, would it make sense to adapt an approach similar to https://github.com/paritytech/substrate/pull/9131?

**Comment by adoerr** [comment]
@ordian it makes totally sense to adapt the GRANDPA gossip limiting / reducing strategies for BEEFY as well. We are planing to do that gradually over time.

Currently, we can not reduce gossip too aggressively because we first have to  hook into the block import queue in order to be able to ask for / process missing justifications.

**Comment by tomusdrw** [comment]
The gossip should be completely overhauled according to https://github.com/paritytech/grandpa-bridge-gadget/blob/td-docs/docs/beefy.md#gossip
